# Generated by Django 3.0.5 on 2020-05-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_category_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='pass_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
