# Generated by Django 3.0.5 on 2020-05-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorsmodel',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.RenameField(
            model_name='authorsmodel',
            old_name='email_address',
            new_name='email',
        ),
    ]
