# Generated by Django 3.0.5 on 2020-05-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20200503_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorsModel',
            new_name='Author',
        ),
    ]
