# Generated by Django 3.0.5 on 2020-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_auto_20200503_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='level',
            field=models.CharField(choices=[('J', 'Junior'), ('M', 'Middle'), ('S', 'Senior')], default='J', max_length=1),
            preserve_default=False,
        ),
    ]
