# Generated by Django 3.0.5 on 2020-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='level',
            field=models.CharField(choices=[('J', 'Junior developer'), ('M', 'Middle developer'), ('S', 'Senior developer')], max_length=1),
        ),
    ]
